export const JurusanData = [
    { label: 'Informatika' },
    { label: 'Teknik Komputer' },
    { label: 'Teknik Elektro' },
    { label: 'Teknik Fisika' },
    { label: 'Sistem Informasi' },
    { label: 'Perhotelan' },
    { label: 'Akuntansi' },
    { label: 'Managemen' },
    { label: 'Komunikasi Strategis' },
    { label: 'Jurnalistik' },
    { label: 'Desain Komunikasi Visual' },
    { label: 'Arsitektur' },
    { label: 'Film & Animasi' },
]

export const DivisiData = [
    { label: 'Dekorasi' },
    { label: 'Publikasi' },
    // { label: 'Keamanan' },
    { label: 'Fresh Money' },
    // { label: 'Sponsor' },
    { label: 'Dokumentasi' },
    { label: 'Acara' },
    // { label: 'Perlengkapan' },
    { label: 'Lomba' },
    // { label: 'Konsumsi' },
    { label: 'Website' },
    { label: 'Visual' },
]
